name: Deploy to S3

on:
  push:
    branches:
      - master  # Replace with the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Sync files to S3 (excluding specific directories/files)
        run: aws s3 sync . s3://abozeman-crc-staticsite-bucket --delete --exclude ".git/*" --exclude ".github/workflows/*" --exclude "README.md"
        env:
          AWS_DEFAULT_REGION: us-east-1  # Replace with your AWS region

